server {
	host			127.0.0.1;
	port			8080;
	max_body_size	10000000;

	error_page		400 var/www/errors/400.html;
	error_page		403 var/www/errors/403.html;
	error_page		404 var/www/errors/404.html;
	error_page		405 var/www/errors/405.html;
	error_page		409 var/www/errors/409.html;
	error_page		500 var/www/errors/500.html;

	location / {
		methods		GET;
		root		var/www/html;
		index		index.html;
		autoindex	off;
	}
	location /uploads/dit {
		methods GET;
		root	var/www/uploads/dit;
		autoindex on;
	}
	location /uploads {
		methods			GET POST DELETE;
		root			var/www/uploads;
		upload_store	var/www/uploads;
		autoindex		on;
	}
	location /cgi-bin {
		methods		GET POST;
		root		var/www/cgi-bin;
		cgi			.php /usr/bin/php-cgi;
	}
}

server {
	host			127.0.0.1;
	port			8081;
	max_body_size	1000;

	error_page		404 var/www/errors/404.html;

	location / {
		methods		GET;
		root		var/www/site2;
		index		index.html;
		autoindex	off;
	}
}

server {
	host 127.0.0.1;
	port 8082;
	max_body_size 1000;

	location / {
		methods GET;
		root var/www/site3;
		index index.html;
		autoindex off;
	}
}

server {
	host            127.0.0.1;
	port            8083;
	max_body_size   1000;

	location / {
		methods     GET;
		root        var/www/site4;
		index       index.html;
		autoindex   off;
	}
		location /uploads {
		methods         GET POST DELETE;
		root            var/www/uploads;
		upload_store    var/www/uploads;
		autoindex       on;
	}
}


server {
	host            127.0.0.1;
	port            8083;
	max_body_size   1000;

	location / {
		methods     GET;
		root        var/www/site4;
		index       index.html;
		autoindex   off;
	}
		location /uploads {
		methods         GET POST DELETE;
		root            var/www/uploads;
		upload_store    var/www/uploads;
		autoindex       on;
	}
}
