server {
	host 127.0.0.1;
	port 8082;
	max_body_size 1000;

	location / {
		methods GET;
		root var/www/site3;
		index index.html;
		autoindex off;
	}
}

server {
	host 127.0.0.1;
	port 8082;
	max_body_size 1000;

	location / {
		methods GET;
		root var/www/site3;
		index index.html;
		autoindex off;
	}
}
